theme = 'paper'

publishDir = '../docs'

baseURL = 'https://andrelom.github.io/endless/'
languageCode = 'en-us'

title = 'André Moraes'

[params]

  color = 'linen'

  github = 'andrelom'
  linkedin = 'in/andrelom'
