baseURL = 'https://andrelom.github.io/endless/'
languageCode = 'en-us'

theme = 'papermod'

publishDir = '../docs'
contentDir = './content'

title = 'André Moraes'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = 'production'
title = 'Endless'
description = 'Endless ideas for Sitecore projects.'
keywords = ['Sitecore', '.NET', 'C#']
author = 'André Moraes'

[params.assets]
disableFingerprinting = true

[params.label]
text = 'André Moraes'

[params.homeInfoParams]
title = 'Endless'
content = 'Endless ideas for Sitecore projects.'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/andrelom/endless'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/andrelom/'

[[params.socialIcons]]
name = 'email'
url = 'mailto:andrelom@gmail.com'

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 3
