baseURL = 'https://andrelom.github.io/endless/'
languageCode = 'en-us'

theme = 'papermod'

publishDir = '../docs'
contentDir = './posts'

title = 'André Moraes'

[minify]
disableXML = true
minifyOutput = true
